const fakeData = {
  term_sheet_matrix: [
      {
        company_name: 'Lender Name',
        date_updated: '12/12/12',
        closing_leverage: '3.5x',
        revolver: '$10M',
        term_loan: '$75M',
        ddtl: '$25M',
        acquistion_facility: '$25M',
        lender_hold_size: 'Awaiting Response',
        term: '5 Years',
        amortization_per_year: '2.5%',
        minimum_sponsor_equity_contribution: '40%',
        interest_rate: 'L+700',
        libor_floor: '0.075%',
        revolver_undrawn_fee: '0.05%',
        ddtl_undrawn_fee: '0.50%',
        call_protection: 'Year 1: 102 (Refi) / 101 (M&A) Year 2+: Par',
        default_rate: '2.0% upon occurrence and continuance of a specified default',
        upfront_fee: '1.75%',
        excess_cash_flow_sweep: '50%',
        sponsor_management_fees_per_year: '$1.25M',
      },
      {
        company_name: 'Lender Name',
        date_updated: '12/12/12',
        closing_leverage: '3.5x',
        revolver: '$10M',
        term_loan: '$75M',
        ddtl: '$25M',
        acquistion_facility: '$25M',
        lender_hold_size: 'Awaiting Response',
        term: '5 Years',
        amortization_per_year: '2.5%',
        minimum_sponsor_equity_contribution: '40%',
        interest_rate: 'L+700',
        libor_floor: '0.075%',
        revolver_undrawn_fee: '0.05%',
        ddtl_undrawn_fee: '0.50%',
        call_protection: 'Year 1: 102 (Refi) / 101 (M&A) Year 2+: Par',
        default_rate: '2.0% upon occurrence and continuance of a specified default',
        upfront_fee: '1.75%',
        excess_cash_flow_sweep: '50%',
        sponsor_management_fees_per_year: '$1.25M',
      },
      {
        company_name: 'Lender Name',
        date_updated: '12/12/12',
        closing_leverage: '3.5x',
        revolver: '$10M',
        term_loan: '$75M',
        ddtl: '$25M',
        acquistion_facility: '$25M',
        lender_hold_size: 'Awaiting Response',
        term: '5 Years',
        amortization_per_year: '2.5%',
        minimum_sponsor_equity_contribution: '40%',
        interest_rate: 'L+700',
        libor_floor: '0.075%',
        revolver_undrawn_fee: '0.05%',
        ddtl_undrawn_fee: '0.50%',
        call_protection: 'Year 1: 102 (Refi) / 101 (M&A) Year 2+: Par',
        default_rate: '2.0% upon occurrence and continuance of a specified default',
        upfront_fee: '1.75%',
        excess_cash_flow_sweep: '50%',
        sponsor_management_fees_per_year: '$1.25M',
      },
      {
        company_name: 'Lender Name',
        date_updated: '12/12/12',
        closing_leverage: '3.5x',
        revolver: '$10M',
        term_loan: '$75M',
        ddtl: '$25M',
        acquistion_facility: '$25M',
        lender_hold_size: 'Awaiting Response',
        term: '5 Years',
        amortization_per_year: '2.5%',
        minimum_sponsor_equity_contribution: '40%',
        interest_rate: 'L+700',
        libor_floor: '0.075%',
        revolver_undrawn_fee: '0.05%',
        ddtl_undrawn_fee: '0.50%',
        call_protection: 'Year 1: 102 (Refi) / 101 (M&A) Year 2+: Par',
        default_rate: '2.0% upon occurrence and continuance of a specified default',
        upfront_fee: '1.75%',
        excess_cash_flow_sweep: '50%',
        sponsor_management_fees_per_year: '$1.25M',
      },
      {
        company_name: 'Lender Name',
        date_updated: '12/12/12',
        closing_leverage: '3.5x',
        revolver: '$10M',
        term_loan: '$75M',
        ddtl: '$25M',
        acquistion_facility: '$25M',
        lender_hold_size: 'Awaiting Response',
        term: '5 Years',
        amortization_per_year: '2.5%',
        minimum_sponsor_equity_contribution: '40%',
        interest_rate: 'L+700',
        libor_floor: '0.075%',
        revolver_undrawn_fee: '0.05%',
        ddtl_undrawn_fee: '0.50%',
        call_protection: 'Year 1: 102 (Refi) / 101 (M&A) Year 2+: Par',
        default_rate: '2.0% upon occurrence and continuance of a specified default',
        upfront_fee: '1.75%',
        excess_cash_flow_sweep: '50%',
        sponsor_management_fees_per_year: '$1.25M',
      },
    ],
  }

  export { fakeData }
